### ISSUE TITLE
integration with asp.net mvc

### ISSUE THREAD

**Issue by mortyyyy** [ivoviz/feedback#17]
How does it integrate with the asp.net mvc and to send data to db?

**Comment by kishoresahas** [comment]
it is really straight forward,  use the post data 

https://github.com/ivoviz/feedback#post-data

**Comment by making3** [comment]
This is old, but I was unable to use an object as a parameter (or even the post data as parameters) in MVC 4, but was able to accept a string and serialize the json to an object::

```cs
public void Send(string feedback)
{
	var model = JsonConvert.DeserializeObject<Feedback>(feedback);
}
```

Either way, this isn't an issue.
