### ISSUE TITLE
the highlight drag functionality is very slow

### ISSUE THREAD

**Issue by mfsi-pallavidhanuka** [ivoviz/feedback#19]
Hi ivoviz,
I found this plugin very cool! I have integrated it with my app using the below code:

<script type="text/javascript">
      $.feedback({
        ajaxURL: BASE_URL+'/feedback/save-feedback',
        html2canvasURL: '/js/lib/html2canvas.min.js'
      });
    </script>

And included the feedback.js, feedback.css and html2canva.js in my files.

However there is an issue, it is very slow. The areas don't get highlighted immdeiately on selecting using the drag feature. What could be a possible reason for this?

Would be very thankful if you could help!

Thanks,
Pallavi

**Comment by flaska** [comment]
Hello ivoviz, 

This is Jacob and I have the same issue as Pallavi.

The select element & drag features are both very slow :(
There is about a 1second delay between where is your mouse cursor and what is actually the selected area.

Thank for any ideas.
