### ISSUE TITLE
integrate with npm and bower 

### ISSUE THREAD

**Issue by evilebottnawi** [ivoviz/feedback#27]

**Comment by justin808** [comment]
Any word on this one? This would be useful.

**Comment by robinsving** [comment]
+1

**Comment by titobf** [comment]
+1

**Comment by ivoviz** [comment]
I'm sorry but I don't have time to maintain this repo. However, I'm totally open to handing over it to another maintainer. :)

**Comment by merlano17** [comment]
@ivoviz  sure i can take it and maintain :)
