### ISSUE TITLE
Created Angular Directive

### ISSUE THREAD

**Issue by jacobscarter** [ivoviz/feedback#29]
Hey @ivoviz,

I just wanted to give you a heads up I am using your repo to create an AngularJS directive.

I am still working on it and going to add a lot of customization features but feel free to check it out at [jacobscarter/angular-feedback](http://github.com/jacobscarter/angular-feedback)

**Comment by ivoviz** [comment]
Hey,

I was thinking about creating an Angular directive as well, but I didn't have time at all. I'm glad you've done it!

**Comment by jacobscarter** [comment]
Awesome, let me know if you have any thoughts on it.
