### ISSUE TITLE
Event Handler Removal Can Cause Issues for other registered handlers

### ISSUE THREAD

**Issue by GraemeSMiller** [ivoviz/feedback#36]
Events like selectstart and eventdrag have handlers added to the document body. They are then removed on close. If other scripts have registered handlers on the document for selectstart etc then removing them will break those scripts. It would be safer to ensure that removing handlers for events added to the document doesn't effect any other handlers. 

Namespacing the events would make the plugin more robust. Happy to do PR to change.

**Comment by ivoviz** [comment]
Hey!

Sadly I don't have time to maintain this project, in fact, I would happily hand it over to someone who would take care of it.

Anyways, if you would do a PR it would be nice!
