### ISSUE TITLE
More information, how to use?

### ISSUE THREAD

**Issue by zgelici** [ivoviz/feedback#53]
Hello,

Before it was a js file, now there are differents files. how do i compile this. there is no readme? 

possible to add a demo page?

Thank you

**Comment by timelf123** [comment]
```
import { Feedback } from '@ivoviz/feedback.js';
const feedback = new Feedback();
feedback.open();
```

**Comment by zgelici** [comment]
ok timelf123 thanks for you answer, but it still dont help me.

self research:
Now i understand how to run it:
i searched on the ts script. its typescript, need to be compiled. 

Thanks

**Comment by iclems** [comment]
Would be great to add a static site with demo

**Comment by ivoviz** [comment]
No promises, but I might have some free time in the upcoming days so I can add a demo site and finish what's left to do in the new version.
